import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,access} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const root=resolve('public'),jobsDir=resolve('.jobs'),python=resolve('.venv/bin/python'),jobs=new Map();let active=null;
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.mp4':'video/mp4'};
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
async function body(req){let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>15*1024*1024)throw Error('Upload must be smaller than 15 MB');chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString())}
function validate(data){if(typeof data.prompt!=='string'||!data.prompt.trim()||data.prompt.length>2000)throw Error('Enter a prompt of 1–2000 characters');const ratio=data.ratio||'16:9';if(!['9:16','16:9','1:1'].includes(ratio))throw Error('Invalid format');if(![9,25,49].includes(data.frames))throw Error('Choose a supported length');if(!Number.isInteger(data.seed)||data.seed<0||data.seed>2147483647)throw Error('Invalid seed');if(data.image&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data.image))throw Error('Image must be PNG, JPG, or WebP');return {...data,width:ratio==='9:16'?256:448,height:ratio==='16:9'?256:ratio==='9:16'?448:448,steps:20}}
await mkdir(jobsDir,{recursive:true});
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1:5173');if(req.headers.host!=='127.0.0.1:5173'&&req.headers.host!=='localhost:5173')return json(res,403,{error:'Use the local app address'});
if(url.pathname.startsWith('/api/')){
if(req.method==='GET'&&url.pathname==='/api/engine'){let installed=true;try{await access(python)}catch{installed=false}return json(res,200,{installed,active,engine:'LTX-Video · local GPU'})}
if(req.method==='POST'){
if(!['http://127.0.0.1:5173','http://localhost:5173'].includes(req.headers.origin))return json(res,403,{error:'Submit from the local app'});
if(url.pathname==='/api/generate'){if(active)return json(res,409,{error:'A generation is already running'});let data;try{data=validate(await body(req))}catch(e){return json(res,400,{error:e.message})}try{await access(python)}catch{return json(res,503,{error:'Install the local runtime first. See README.'})}const id=randomUUID(),dir=resolve(jobsDir,id);await mkdir(dir);const config={...data,output_path:resolve(dir,'output.mp4')};delete config.image;if(data.image){config.image_path=resolve(dir,'input.png');await writeFile(config.image_path,Buffer.from(data.image.split(',')[1],'base64'))}const configPath=resolve(dir,'job.json');await writeFile(configPath,JSON.stringify(config));const job={id,status:'running',stage:'Starting local GPU',step:null,total:null};jobs.set(id,job);active=id;const child=spawn(python,[resolve('engine/generate.py'),configPath],{cwd:process.cwd(),env:{...process.env,HF_HOME:resolve('.models'),PYTORCH_ENABLE_MPS_FALLBACK:'1'}});job.child=child;let buffer='',errors='';child.stdout.on('data',chunk=>{buffer+=chunk;let lines=buffer.split('\n');buffer=lines.pop();for(const line of lines)try{const p=JSON.parse(line);job.stage=p.stage;job.step=p.step;job.total=p.total}catch{}});child.stderr.on('data',c=>{errors=(errors+c.toString()).slice(-4000)});child.on('error',e=>{job.status='failed';job.stage=e.message;active=null});child.on('close',async code=>{active=null;if(job.status==='cancelled')return;if(code===0){try{await access(config.output_path);job.status='complete';job.url='/api/jobs/'+id+'/video';job.stage='Complete'}catch{job.status='failed';job.stage='Worker produced no video'}}else{job.status='failed';if(!job.stage.startsWith('Failed:'))job.stage=errors.slice(-1000)||'Generation failed'}});return json(res,202,{id,status:'running'})}
let match=url.pathname.match(/^\/api\/jobs\/([a-f0-9-]+)\/cancel$/);if(match){const job=jobs.get(match[1]);if(!job)return json(res,404,{error:'Job not found'});if(job.status==='running'){job.status='cancelled';job.stage='Cancelled';job.child.kill('SIGTERM')}return json(res,200,{status:job.status})}}
let match=url.pathname.match(/^\/api\/jobs\/([a-f0-9-]+)(\/video)?$/);if(req.method==='GET'&&match){let job=jobs.get(match[1]);if(!job)return json(res,404,{error:'Job not found'});if(match[2]){if(job.status!=='complete')return json(res,409,{error:'Video is not ready'});res.writeHead(200,{'Content-Type':'video/mp4'});res.end(await readFile(resolve(jobsDir,job.id,'output.mp4')));return}let {child,...publicJob}=job;return json(res,200,publicJob)}return json(res,404,{error:'Not found'})}
if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);res.end();return}let path=resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!path.startsWith(root+sep)){res.writeHead(403);res.end();return}const data=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(req.method==='HEAD'?undefined:data)}catch{if(!res.headersSent){res.writeHead(404);res.end('Not found')}else res.end()}});
server.listen(5173,'127.0.0.1',()=>console.log('Animation Engine: http://127.0.0.1:5173'));
process.on('SIGINT',()=>{for(const job of jobs.values())if(job.status==='running')job.child.kill();server.close(()=>process.exit())});
export {validate};
